version: "3"
services:
  access:
    image: 192.168.202.12:5000/{{ .Domain }}/access
    deploy:
      mode: global
      placement: { constraints: [ node.labels.hasAccess==true ] }
    volumes: [ "logs:/var/log/nginx" ]
    ports: ["80:80"]
  logc:
    image: 192.168.202.12:5000/xiaomei/logc
    command: [ "org-name" ]
    deploy:
      mode: global
    volumes: 
      - "logs:/home/ubuntu/logc/log"
      - "example_logs:/logs/example"
volumes:
  logs:
  example_logs:
    external: true
