stages:
  - deploy

deploy-qa:
  stage: deploy
  tags:
    - shell-xiaomei-qa  # match shell runner for qa that has xiaomei command.
  script:
    - xiaomei logc deploy $CI_ENVIRONMENT_NAME -Wb "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY"
  environment:
    name: $CI_COMMIT_REF_NAME
  only:
    refs: [ branches ]
    variables: [ '$CI_COMMIT_REF_NAME == "qa"' ]

deploy-production:
  stage: deploy
  tags:
    - shell-xiaomei-production # match shell runner for production that has xiaomei command.
  script:
    - xiaomei logc deploy production -Wb "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY"
  environment:
    name: production
  only:
    refs: [ branches ]
    variables: [ '$CI_COMMIT_REF_NAME == "master"' ]
  when: manual
  allow_failure: false

before_script:
  - buildDir=$(pwd); echo $buildDir
  - projectDir=~/oam/{{ .ProName }}; echo $projectDir
  - mkdir -p $(dirname $projectDir); ln -sfT $buildDir $projectDir; cd $projectDir

