language: go
go:
  - "1.10"
install:
  - go get -t ./...
  - go get github.com/mattn/goveralls
script:
  - go test -covermode=count -coverprofile=coverage.out ./...
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
