defaults: &defaults
  timeZone: { name: China, offset: 28800 }
  # mailer://smtp.exmail.qq.com:587/?user=报警<alarm@{{.Domain }}>&pass=123456
  mailer: "mailer://smtp.qq.com:25/?user=小美<xiaomei-go@qq.com>&pass=zjsbosjlhgugechh"
  keepers: [ "小美<xiaomei-go@qq.com>" ]

name: {{ .ProName }}
envs:
  dev:
    <<: *defaults
    domain: {{ .ProNameUrlSafe }}.api.dev.{{ .Domain }}
    secret: {{ genSecret }}
    keepers: [ ]
  test:
    <<: *defaults
    domain: localhost:3000
    secret: {{ genSecret }}
    keepers: [ ]
  ci:
    <<: *defaults
    domain: localhost:3000
    secret: {{ genSecret }}
  qa:
    <<: *defaults
    https: true
    domain: {{ .ProNameUrlSafe }}.api.qa.{{ .Domain }}
    secret: {{ genSecret }}
  preview:
    <<: *defaults
    https: true
    domain: {{ .ProNameUrlSafe }}.api.preview.{{ .Domain }}
    secret: {{ genSecret }}
  production:
    <<: *defaults
    https: true
    domain: {{ .ProNameUrlSafe }}.api.{{ .Domain }}
    secret: {{ genSecret }}

