name: {{ .ProName }}
envs:
  dev:
    <<: *defaults
    domain: {{ .ProNameUrlSafe }}.dev.example.com
    keepers: [ ]
  test:
    <<: *defaults
    domain: {{ .ProNameUrlSafe }}.test.example.com
    keepers: [ ]
  demo:
    <<: *defaults
    domain: {{ .ProNameUrlSafe }}.demo.example.com
  qa:
    <<: *defaults
    https: true
    domain: {{ .ProNameUrlSafe }}.qa.example.com
  preview:
    <<: *defaults
    https: true
    domain: {{ .ProNameUrlSafe }}.preview.example.com
  production:
    <<: *defaults
    https: true
    domain: {{ .ProNameUrlSafe }}.example.com
    secret: {{ .Secret }}

defaults: &defaults
  timeZone: { name: China, offset: 28800 }
  mailer: "mailer://smtp.qq.com:25/?user=小美<xiaomei-go@qq.com>&pass=zjsbosjlhgugechh"
  keepers: [ "小美<xiaomei-go@qq.com>" ]

