name: {{ .ProName }}
envs:
  dev:
    <<: *defaults
    domain: {{ .ProNameUrlSafe }}.dev
    keepers: [ ]
  test:
    <<: *defaults
    domain: {{ .ProNameUrlSafe }}.test
    keepers: [ ]
  demo:
    <<: *defaults
    domain: {{ .ProNameUrlSafe }}.demo
  qa:
    <<: *defaults
    domain: {{ .ProNameUrlSafe }}.qa
  preview:
    <<: *defaults
    domain: {{ .ProNameUrlSafe }}.preview
  prouduction:
    <<: *defaults
    domain: {{ .ProNameUrlSafe }}.com
    secret: {{ .Secret }}

defaults: &defaults
  timeZone: { name: China, offset: 28800 }
  mailer: "mailer://smtp.qq.com:25/?user=小美<xiaomei-go@qq.com>&pass=zjsbosjlhgugechh"
  keepers: [ "小美<xiaomei-go@qq.com>" ]

