name: {{ .ProName }}
timeZone: { name: China, offset: 28800 }
mailer:
  host: imap.exmail.qq.com
  port: 25
  sender: "xiaomei<xiaomei-go@qq.com>"
  passwd: abc123
keepers: [ "xiaomei<xiaomei-go@qq.com>" ]

