services:
  app:
    image: 192.168.202.12:5000/{{ .Domain }}/app
    ports: "3001-3002"
    volumes: [ "{{ .ProName }}_logs:/home/ubuntu/{{ .ProName }}/log" ]
  web:
    image: 192.168.202.12:5000/{{ .Domain }}/web
    ports: "8001"
    volumes: [ "{{ .ProName }}_logs:/var/log/nginx" ]

volumesToCreate: [ "{{ .ProName }}_logs" ]

environments:
  dev:
  qa:
  production:


