version: "3"
services:
  app:
    image: 192.168.202.12:5000/{{ .Domain }}/app
    deploy:
      replicas: 2
    volumes: ["logs:/home/ubuntu/logs"]
  web:
    image: 192.168.202.12:5000/{{ .Domain }}/web
    depends_on: [ app ]
    deploy:
      ports: [ "8001:80" ]
      mode: global
      placement: { constraints: [ hasAccess==true ] }
    volumes: ["logs:/var/log/nginx"]

volumes:
  logs:
