version: "3"
services:
  app:
    image: 192.168.202.12:5000/{{ .Domain }}/app
    deploy:
      replicas: 2
      update_config:
        monitor: 1m
    volumes: ["logs:/home/ubuntu/{{ .ProName }}/log"]
  web:
    image: 192.168.202.12:5000/{{ .Domain }}/web
    ports: [ "8001:8000" ]
    depends_on: [ app ]
    deploy:
      replicas: 2
      placement: { constraints: [ node.labels.hasAccess==true ] }
      update_config:
        monitor: 5s
    volumes: ["logs:/var/log/nginx"]

volumes:
  logs:
