version: "3"
registry: 192.168.202.12:5000
services:
  app:
    deploy:
      replicas: 2
    volumes: ["logs:/home/ubuntu/logs"]
  web:
    depends_on: [ "app" ]
    deploy:
      replicas: 2
    volumes: ["logs:/var/log/nginx"]

volumes:
  logs:
