name: {{ .ProName }}
envs:
  dev:
    domain: {{ .ProNameUrlSafe }}.dev.{{ .Domain }}
    timeZone: { name: China, offset: 28800 }
  qa:
    https: true
    domain: {{ .ProNameUrlSafe }}.qa.{{ .Domain }}
    timeZone: { name: China, offset: 28800 }
  preview:
    https: true
    domain: {{ .ProNameUrlSafe }}.preview.{{ .Domain }}
    timeZone: { name: China, offset: 28800 }
  production:
    https: true
    domain: {{ .ProNameUrlSafe }}.{{ .Domain }}
    timeZone: { name: China, offset: 28800 }

