appName: example
appPort: 3000
appStartTimeout: 10

timeZoneName: China
timeZoneOffset: 28800
mailer:
  host: imap.exmail.qq.com
  port: 25
  sender: xiaomei<xiaomei-go@qq.com>
  passwd: abc123

alarmReceivers: [ 'xiaomei<xiaomei-go@qq.com>' ]

deployUser: ubuntu
deployRoot: /apps
gitAddr: git@github.com:/replace-me-with-git-addr.git
gitBranch: 

