appName: example
appPort: 3000
appStartTimeout: 10

timeZoneName: China
timeZoneOffset: 28800
mailer:
  host: imap.exmail.qq.com
  port: 25
  sender: data-system<data-system@retail-tek.com>
  passwd: RetailBigdata1234

# alarmReceivers: [ 'name<email@example.com>' ] 

deployUser: ubuntu
deployRoot: /apps
gitAddr: git@gitlab.retail-tek.com:go/reports.git
gitBranch: 

