app:
  name: example
  port: 3000
  startTimeout: 10s

  timeZone:
    name: China
    offset: 28800
  mailer:
    host: imap.exmail.qq.com
    port: 25
    sender: xiaomei<xiaomei-go@qq.com>
    passwd: abc123
  keepers: [ 'xiaomei<xiaomei-go@qq.com>' ]

deploy:
  user: ubuntu
  root: /apps
  gitAddr: git@github.com:/replace-me-with-git-addr.git
  gitBranch: 

