app:
  name: example
  port: 3000
  dockerImage: bughou/xiaomei-appserver
  startTimeout: 10s

  timeZone:
    name: China
    offset: 28800
  mailer:
    host: imap.exmail.qq.com
    port: 25
    sender: { name: xiaomei, addr: xiaomei-go@qq.com }
    passwd: abc123
  keepers: [ { name: xiaomei, addr: xiaomei-go@qq.com } ]

deploy:
  user: ubuntu
  root: /apps
  gitAddr:
  gitBranch:

godoc:
  domain: godoc.dev
  port: 1234
  indexInterval: -1
