app:
  env:    dev
  domain: example-dev.org
  keepers: [ ]

db:
  mysql:
    default: root:root@tcp(127.0.0.1:3306)/example
  redis:
    default: redis://:@localhost:6379/0

servers:
  - addr: 127.0.0.1
    appAddr: 0.0.0.0
    tasks: setup-nginx setup-appserver
    appStartOn: (started mysql and started redis-server)

