version: "3"
registry: 192.168.202.12:5000
services:
  app:
    ports: [ "3000:3000" ]
    deploy:
      replicas: 1
    volumes: [ ./log:/home/ubuntu/appserver/log ]
# web:
#   deploy:
#     replicas: 1
