stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - docker-xiaomei  # match docker runner that use xiaomei image.
  script:
    - go build
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\bno-ci\b/i

test:
  stage: test
  tags:
    - docker-xiaomei  # match docker runner that use xiaomei image.
  services:
#   - name: postgres:10 # url: postgres://postgres:pass@postgres/postgres?sslmode=disable
#   - name: redis:3.2   # url: redis://:@redis/0
  variables:
#   POSTGRES_PASSWORD: pass
  script:
#   - xiaomei psql create ci
    - GOENV=ci go test ./models/... -p 1 -gcflags=-l -coverprofile .test.cover
    - go tool cover -func=.test.cover | tail -n 1
  coverage: '/total:\s+\(statements\)\s+(\d+.\d+\%)/'
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\bno-ci\b/i

deploy-qa:
  stage: deploy
  tags:
    - shell-xiaomei-qa  # match shell runner for qa that has xiaomei command.
  script:
    - xiaomei app deploy $CI_ENVIRONMENT_NAME --no-wait
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://{{ .ProNameUrlSafe }}.api-$CI_COMMIT_REF_NAME.{{ .Domain }}
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_REF_NAME == 'qa'
      - $CI_COMMIT_REF_NAME == 'qa2'
      - $CI_COMMIT_REF_NAME == 'uat'
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\bno-c[id]\b/i

deploy-production:
  stage: deploy
  tags:
    - shell-xiaomei-production # match shell runner for production that has xiaomei command.
  script:
    - xiaomei app deploy production --no-wait
  environment:
    name: production
    url: https://{{ .ProNameUrlSafe }}.api.{{ .Domain }}
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_REF_NAME == 'master'
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\bno-c[id]\b/i
  when: manual


before_script:
  - buildDir=$(pwd) && echo $buildDir
  - projectDir=$(go env GOPATH)/src/{{ .Domain }}/{{ .ProName }} && echo $projectDir
  - mkdir -p $(dirname $projectDir) && ln -sf $buildDir $projectDir && cd $projectDir

