stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - docker-xiaomei  # match docker runner that use xiaomei image.
  script:
    - go build
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^(qa|qa2|uat|master)$/'
      when: on_success
    - changes:
        - "**/*.go"
      when: on_success
    - when: never

test:
  stage: test
  tags:
    - docker-xiaomei  # match docker runner that use xiaomei image.
  services:
#   - name: postgres:10 # url: postgres://postgres:pass@postgres/postgres?sslmode=disable
#   - name: redis:3.2   # url: redis://:@redis/0
  variables:
#   POSTGRES_PASSWORD: pass
  script:
#   - xiaomei psql create ci
    - GOENV=ci go test ./... -p 1 -gcflags=-l -coverprofile .test.cover
    - go tool cover -func=.test.cover | tail -n 1
  coverage: '/total:\s+\(statements\)\s+(\d+.\d+\%)/'
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^(qa|qa2|uat|master)$/'
      when: on_success
    - changes:
        - "**/*.go"
        - release/img-app/config/config.yml
        - release/img-app/config/env/ci.yml
      when: on_success
    - when: never

deploy-qa:
  stage: deploy
  tags:
    - shell-xiaomei-qa  # match shell runner for qa that has xiaomei command.
  script:
#   - xiaomei psql create $CI_ENVIRONMENT_NAME
    - xiaomei app deploy $CI_ENVIRONMENT_NAME -Wb "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY"
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://{{ .ProNameUrlSafe }}.api.$CI_COMMIT_REF_NAME.{{ .Domain }}
  only:
    refs: [ branches ]
    variables: [ '$CI_COMMIT_REF_NAME =~ /^(qa|qa2|uat)$/' ]

deploy-production:
  stage: deploy
  tags:
    - shell-xiaomei-production # match shell runner for production that has xiaomei command.
  script:
#   - xiaomei psql create production
    - xiaomei app deploy production -Wb "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY"
  environment:
    name: production
    url: https://{{ .ProNameUrlSafe }}.api.{{ .Domain }}
  only:
    refs: [ branches ]
    variables: [ '$CI_COMMIT_REF_NAME == "master"' ]
  when: manual
  allow_failure: false

before_script:
  - buildDir=$(pwd); echo $buildDir
  - projectDir=$(go env GOPATH)/src/{{ .ProPath }}; echo $projectDir
  - mkdir -p $(dirname $projectDir); ln -sfT $buildDir $projectDir; cd $projectDir

