stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - xiaomei  # match gitlab-runner that use xiaomei docker image.
  script:
    - go build

deploy:
  stage: deploy
  tags:
    - shell
  script:
    - xiaomei app deploy $CI_ENVIRONMENT_NAME
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://{{ .ProNameUrlSafe }}.$CI_COMMIT_REF_NAME.example.com
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_REF_NAME == 'qa'
      - $CI_COMMIT_REF_NAME == 'qa2'
      - $CI_COMMIT_REF_NAME == 'uat'

deploy-production:
  stage: deploy
  tags:
    - shell
  script:
    - xiaomei app deploy production
  environment:
    name: production
    url: https://{{ .ProNameUrlSafe }}.example.com
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_REF_NAME == 'master'
  when: manual


before_script:
  - buildDir=$(pwd) && echo $buildDir
  - projectDir=$(go env GOPATH)/src/example.com/{{ .ProName }} && echo $projectDir
  - mkdir -p $(dirname $projectDir) && ln -sf $buildDir $projectDir && cd $projectDir

