stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - shell
  script:
    - xiaomei web deploy $CI_ENVIRONMENT_NAME --no-wait
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://{{ .ProNameUrlSafe }}.$CI_COMMIT_REF_NAME.{{ .Domain }}
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_REF_NAME == 'qa'
      - $CI_COMMIT_REF_NAME == 'qa2'
      - $CI_COMMIT_REF_NAME == 'uat'

deploy-production:
  stage: deploy
  tags:
    - shell
  script:
    - xiaomei web deploy production --no-wait
  environment:
    name: production
    url: https://{{ .ProNameUrlSafe }}.{{ .Domain }}
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_REF_NAME == 'master'
  when: manual

